import {empty,changed,copy,freshRecord,validate,resolve,equal} from './model.js';
import {read,mutate,forget} from './store.js';
import {Cloud,configCheck} from './api.js';
import {synchronize} from './sync.js';
import {prepareImport} from './import.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cloud=null,key='local',state,view='contacts',selected=null,filter='',trash=false,busy=false,syncError='',auto=true;
const label=k=>({where_met:'Event / where met',met_date:'Meeting date',contact_types:'Contact types',context_notes:'Things to remember',warmth_reason:'Why this rating?',occurred_at:'Conversation date',followup:'Follow-up task, date, status and owner',deleted:'Archived','$record':'Whole contact (archive/edit or identity conflict)'}[k]||k[0].toUpperCase()+k.slice(1));
const status=r=>r.conflict?'Needs review':r.attempt||changed(r.base?.data,r.draft).length?'Saved on device · pending sync':'Synced';
const today=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};
function toast(t){$('#notice').textContent=t;}
function err(e){toast(e.message||String(e));}
function sessionConfig(){try{const c=JSON.parse(localStorage.getItem('cm-v3-config')||'null');if(c){cloud=new Cloud(c);if(cloud.session?.user?.id)key=c.url+'|'+cloud.session.user.id;}}catch(e){err(e);}}
async function refresh(){state=await read(key);render();}
function pending(){return Object.values(state.contacts).filter(r=>r.attempt||changed(r.base?.data,r.draft).length).length+Object.values(state.notes).filter(n=>!n.synced).length;}
function top(){return `<div class="toolbar"><nav class="actions"><button data-action="contacts">People</button><button data-action="settings">Workspace & sync</button></nav><div class="statusline">${!navigator.onLine?'Offline · edits stay on this device':key==='local'?'Local workspace · cloud not connected':`${busy?'Syncing…':syncError?'Sync needs attention':pending()?`${pending()} pending changes`:'All changes synced'}`} ${key!=='local'?'<button data-action="sync" '+(busy?'disabled':'')+'>Sync now</button>':''}</div></div>${syncError?`<div class="notice error">${esc(syncError)} Local edits are preserved. Use Sync now to retry, or sign in again.</div>`:''}`;}
function render(){
 if(!state)return;
 $('#main').innerHTML=top()+(view==='settings'?settings():selected?detail():contacts());
 const search=$('#search');if(search){search.value=filter;search.oninput=()=>{filter=search.value;$('#cards').innerHTML=cards();};}
}
function contacts(){const all=Object.values(state.contacts),active=all.filter(r=>!r.draft.deleted);return `<p class="eyebrow">MAKE THE MOMENT COUNT</p><h1>Your next conversation starts here.</h1><p class="sub">A name, a shared interest, a reason to reconnect. Save the details while they’re fresh.</p><div class="stats"><span>${active.length} people</span><span>${all.filter(r=>r.conflict).length} need review</span><span>${active.filter(r=>r.draft.followup.date&&r.draft.followup.date<=today()&&!['done','closed'].includes(r.draft.followup.status)).length} follow-ups due</span></div><div class="panel"><label>Today’s event<input id="event" placeholder="e.g. Fall career fair" value="${esc(state.event)}"></label><div class="actions"><button data-action="save-event">Remember event</button><button class="primary" data-action="add">＋ Add a person</button><span class="meta">Reused for new contacts; edit it anytime.</span></div></div><div class="toolbar"><label class="search">Search your people<input id="search" type="search" placeholder="Name, company, event, notes…"></label><button data-action="trash">${trash?'Show active':'Show archived'}</button></div><div id="cards">${cards()}</div>`;}
function cards(){const list=Object.values(state.contacts).filter(r=>r.draft.deleted===trash&&JSON.stringify(r.draft).toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>a.draft.name.localeCompare(b.draft.name));return list.length?list.map(r=>`<article class="card"><div><h3>${esc(r.draft.name)}</h3><div class="meta">${esc([r.draft.role,r.draft.company].filter(Boolean).join(' · '))}</div><p class="row-note">${esc(r.draft.followup.action||r.draft.where_met||'Room for a new conversation.')}</p><span class="pill">${esc(key==='local'&&!r.conflict?'Saved on this device':status(r))}</span> <span class="meta">${esc(r.draft.followup.date)}</span></div><button data-action="open" data-id="${r.id}">Open</button></article>`).join(''):`<div class="empty"><h2>${filter?'No matches yet.':trash?'Nothing archived.':'Start with one person.'}</h2><p>${filter?'Try a different name or company.':'Add a contact now, or import your V2 JSON in Workspace & sync.'}</p></div>`;}
function detail(){const r=state.contacts[selected];if(!r){selected=null;return contacts();}const c=r.draft,f=c.followup;return `<button data-action="back">← Your people</button><p class="eyebrow">${esc(c.where_met||'YOUR CONNECTION')}</p><h1>${esc(c.name)}</h1><p class="sub">${esc([c.role,c.company].filter(Boolean).join(' · '))}</p><span class="pill">${esc(key==='local'?'Saved on this device':status(r))}</span><div class="actions"><button class="primary" data-action="edit" data-id="${r.id}">Edit contact</button><button data-action="note" data-id="${r.id}">Log conversation / note</button><button data-action="outreach" data-id="${r.id}">Write a follow-up</button><button data-action="archive" data-id="${r.id}">${c.deleted?'Restore contact':'Archive contact'}</button>${r.conflict?`<button class="primary" data-action="resolve" data-id="${r.id}">Review conflicting edits</button>`:''}</div>${r.conflict?'<div class="notice warn">Another device changed this contact. Both versions are preserved. Review the conflict before making further edits here.</div>':''}<div class="grid"><section class="panel"><h2>The next step</h2><p class="detail-line">${esc(f.action||'No next step set.')}</p><p>${f.date?esc(f.date):'No date'} · ${f.owner==='them'?'Waiting on them':'My turn'} · ${esc(f.status)}</p><button data-action="edit" data-id="${r.id}">Update follow-up</button></section><section class="panel"><h2>Good to remember</h2><p class="detail-line">${esc(c.context_notes||'Add something you want to remember.')}</p><p class="meta">${esc(c.contact_types)} · ${esc(c.warmth)}</p><p>${esc(c.warmth_reason)}</p></section></div><section class="panel"><h2>Contact details</h2>${['email','phone','links','tags','met_date'].filter(k=>c[k]).map(k=>`<p class="detail-line"><strong>${label(k)}:</strong> ${esc(c[k])}</p>`).join('')||'<p>No details added yet.</p>'}</section><section class="panel"><h2>Conversation history</h2>${Object.values(state.notes).filter(n=>n.contact_id===r.id).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).map(n=>`<div class="history"><div class="meta">${esc(n.kind)} · ${esc(n.occurred_at)} · ${n.synced?'Synced':'Saved on device'}</div><p class="detail-line">${esc(n.body)}</p></div>`).join('')||'<p class="sub">Your next conversation belongs here.</p>'}</section>`;}
function settings(){return `<p class="eyebrow">YOUR WORKSPACE</p><h1>Your data, your choice.</h1><p class="sub">V3 saves on this device first. Optional sync uses your own Supabase Free project.</p><div class="notice">Use a trusted personal device. This browser stores contacts and sign-in tokens locally. Export regularly: clearing browser data can erase edits that have not synced. Sync is not a backup.</div><section class="panel"><h2>${key==='local'?'Local workspace':'Connected workspace'}</h2><p class="meta">${key==='local'?'No data leaves this device unless you export it.':esc(cloud?.session?.user?.email||'Signed in')+' · '+esc(cloud?.config.url)}</p><p>Last completed sync: ${esc(state.lastSync||'Not yet')}</p><div class="actions"><button data-action="configure">${cloud?'Configure / sign in':'Connect your cloud'}</button>${key!=='local'?'<button data-action="signout">Sign out locally</button>':''}<button data-action="export">Export full V3 backup</button><button data-action="import">Import V2 JSON / V3 backup</button><button class="danger" data-action="forget">Remove this device’s cached workspace</button></div></section><section class="panel"><h2>Designed for the event</h2><p>Open this app once online before the event so it can save the app shell. On your phone, add it to the home screen from the browser menu. Capture and edit offline; sync resumes when the app is open and online.</p><p>Phone and desktop must use the same Supabase project and account. Each browser origin has a separate offline cache. Use a stable HTTPS URL for actual phone use.</p><p>Cloud setup: run <code>supabase/schema.sql</code> in your own project, create your email/password user in its Auth dashboard, then enter only the project URL and publishable key here. No service-role key, credit card, or paid upgrade is needed by this app.</p></section><section class="panel"><h2>V2 stays yours</h2><p>Importing copies records; it never edits the V2 SQLite file. Google tokens are never imported or synchronized. Gmail/Calendar actions remain available in V2; mobile OAuth and recurring check-ins are outside this pilot.</p><p>New notes append independently. Different contact fields merge; competing edits to the same field require review. Follow-up details are resolved together. Archive is recoverable; there is no permanent contact-delete action.</p></section>`;}
function input(k,value,type='text',extra=''){return `<label>${esc(label(k))}<input name="${k}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(k,value,options){return `<label>${esc(label(k))}<select name="${k}">${options.map(v=>`<option value="${v}" ${value===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function modal(title,body,handler,submit='Save',extras=''){
 $('#dialog-content').innerHTML=`<form id="form"><div class="close-row"><h2>${esc(title)}</h2><button type="button" data-action="close" aria-label="Close dialog">×</button></div>${body}<p id="form-error" class="notice error" hidden role="alert"></p><div class="actions"><button class="primary" type="submit">${esc(submit)}</button>${extras}<button type="button" data-action="close">Cancel</button></div></form>`;$('#dialog').showModal();
 $('#form').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('#form-error').hidden=true;try{await handler(new FormData(e.target),btn.value);if($('#dialog').open)$('#dialog').close();await refresh();}catch(error){$('#form-error').textContent=error.message;$('#form-error').hidden=false;}finally{btn.disabled=false;}};
}
function edit(id){const r=id?state.contacts[id]:null;if(r?.conflict)throw Error('Resolve this contact’s conflicting edits first.');const d=copy(r?.draft||{...empty(),where_met:state.event,met_date:today()});
 modal(id?'Keep the details current.':'A new connection.',`<div class="grid">${input('name',d.name,'text','required maxlength="200" autofocus')}${input('company',d.company)}${input('email',d.email,'email')}${input('where_met',d.where_met)}<label class="full">One thing to remember<textarea name="context_notes">${esc(d.context_notes)}</textarea></label><h3 class="full">The next step</h3>${input('action',d.followup.action)}${input('date',d.followup.date,'date')}<details class="full" ${id?'open':''}><summary>More details & follow-up settings</summary><div class="grid">${input('role',d.role)}${input('phone',d.phone,'tel')}${input('met_date',d.met_date,'date')}${input('links',d.links)}${input('contact_types',d.contact_types)}${input('tags',d.tags)}${select('warmth',d.warmth,['unrated','cold','warm','hot'])}${input('warmth_reason',d.warmth_reason)}${select('status',d.followup.status,['new','pending','sent','replied','scheduled','closed','done'])}${select('owner',d.followup.owner,['me','them'])}</div></details></div><p class="meta">Owner “me” means my turn; “them” means waiting for a reply. No date is assumed.</p>`,async(form,again)=>{
 const data=Object.fromEntries(form);const followup={action:data.action,date:data.date,status:data.status,owner:data.owner};for(const k of ['action','date','status','owner'])delete data[k];const next=validate({...d,...data,followup});const target=id||crypto.randomUUID();
 await mutate(key,s=>{if(id){const latest=s.contacts[id];if(latest.conflict)throw Error('A conflict arrived. Close this form and review it.');if(!equal(latest.draft,d))throw Error('This contact changed while the form was open. Close and reopen it to keep both edits.');latest.draft=next;}else s.contacts[target]=freshRecord(next,target);});
 selected=again?null:target;toast('Saved on this device.');kick();if(again)setTimeout(()=>edit(),0);
 },id?'Save changes':'Save contact',!id?'<button type="submit" value="again">Save and add another</button>':'');
}
function note(id){modal('Keep the conversation.',`<div class="grid">${select('kind','met',['met','call','text','email','linkedin','note','other'])}${input('occurred_at',today(),'date','required')}<label class="full">What happened?<textarea name="body" required maxlength="20000"></textarea></label></div><p class="meta">History entries append independently. Internal notes do not claim contact took place.</p>`,async f=>{const n={...Object.fromEntries(f),id:crypto.randomUUID(),contact_id:id,synced:false};await mutate(key,s=>{s.notes[n.id]=n;});toast('History saved on this device.');kick();},'Add to history');}
function conflict(id){const r=state.contacts[id],remote=r.conflict.contact;if(!remote)throw Error('Remote contact unavailable. Export your backup before continuing.');modal('Keep the right version.',`<p>Both versions are safe. Choose for each conflicting field. Unrelated changes merge automatically. This decision is checked again during sync.</p>${r.conflict.fields.map(k=>`<fieldset><legend>${esc(label(k))}</legend><div class="conflict-values"><label><input type="radio" name="${k}" value="mine" required>Keep this device<br>${esc(show(k==='$record'?r.draft:r.draft[k]))}</label><label><input type="radio" name="${k}" value="remote" required>Keep cloud version<br>${esc(show(k==='$record'?remote.data:remote.data[k]))}</label></div></fieldset>`).join('')}`,async f=>{await mutate(key,s=>{const current=s.contacts[id];if(!equal(current.conflict,r.conflict))throw Error('Conflict changed; reopen review.');s.audit.push({at:new Date().toISOString(),type:'resolution',contact_id:id,choices:Object.fromEntries(f),local:copy(current.draft),remote:copy(remote)});s.contacts[id]=resolve(current,Object.fromEntries(f));});toast('Decision saved locally; server will check for newer edits.');kick();},'Save resolution');}
function show(v){if(v===null||v===undefined||v==='')return '(empty)';if(typeof v==='boolean')return v?'Yes':'No';if(typeof v==='object')return Object.entries(v).map(([k,value])=>`${label(k)}: ${show(value)}`).join('\n');return String(v);}
function configure(){modal('Connect your own workspace.',`<p>Use your own Supabase Free project. Create your user in Authentication → Users first. This app does not sign you up for paid services.</p><div class="grid">${input('url',cloud?.config.url||'','url','required placeholder="https://PROJECT.supabase.co"')}${input('key',cloud?.config.key||'','text','required placeholder="Publishable key"')}${input('email',cloud?.session?.user?.email||'','email','required autocomplete="username"')}${input('password','','password','required autocomplete="current-password"')}</div><label class="check"><input name="trusted" type="checkbox" required>This is my trusted device; save sign-in and offline contacts here.</label><p class="meta">Connecting opens a separate account workspace. Local-only records stay local until you explicitly export/import them. Use the same project and account on both devices.</p>`,async f=>{if(busy)throw Error('Wait for synchronization to finish before switching accounts.');const c=configCheck({url:f.get('url'),key:f.get('key')});const next=new Cloud(c);await next.signin(f.get('email'),f.get('password'));cloud=next;localStorage.setItem('cm-v3-config',JSON.stringify(c));key=c.url+'|'+cloud.session.user.id;selected=null;syncError='';auto=true;toast('Connected. Import your data when you are ready to upload it.');setTimeout(()=>runSync(),0);},'Sign in');}
function outreach(id){const c=state.contacts[id].draft;modal('Make it personal.',`<label>Starting point<select id="template"><option value="thank">Thank you after meeting</option><option value="advice">Ask for a career conversation</option><option value="follow">Gentle follow-up</option></select></label><label>Your message<textarea id="message" rows="10"></textarea></label><button type="button" id="open-mail">Open as email draft</button><p class="meta">Edit the specifics, then open it as a draft in your email app or copy it. Nothing is sent or logged automatically.</p>`,async()=>{const text=$('#message').value;try{await navigator.clipboard.writeText(text);toast('Copied. Paste into your email or messaging app.');}catch{throw Error('Clipboard unavailable. Select and copy the message manually.');}},'Copy message');const templates={thank:`Hi ${c.name},\n\nIt was nice meeting you${c.where_met?' at '+c.where_met:''}. I appreciated our conversation about [specific topic].\n\n[Personal next step or thank-you.]\n\nBest,\n[Your name]`,advice:`Hi ${c.name},\n\nI’m exploring [field or role] and would value hearing about your experience${c.company?' at '+c.company:''}. Would you be open to a brief conversation in the next few weeks?\n\nThank you,\n[Your name]`,follow:`Hi ${c.name},\n\nI wanted to follow up on [specific conversation or request]. [Brief relevant update.]\n\nIf now isn’t a good time, no worries. Thank you for considering it.\n\nBest,\n[Your name]`};const subjects={thank:`Great meeting you${c.where_met?' at '+c.where_met:''}`,advice:`Quick question about your work${c.company?' at '+c.company:''}`,follow:'Following up'};$('#message').value=templates.thank;$('#template').onchange=e=>$('#message').value=templates[e.target.value];$('#open-mail').onclick=()=>{location.href=`mailto:${(c.email||'').replace(/[^\w.+@-]/g,'')}?subject=${encodeURIComponent(subjects[$('#template').value])}&body=${encodeURIComponent($('#message').value)}`;};}
function download(){const blob=new Blob([JSON.stringify({format:'contact-manager-v3',version:1,exported_at:new Date().toISOString(),workspace:state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`contact-manager-v3-${today()}.json`;a.hidden=true;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('Backup download requested. Keep it private; it includes notes and conflict history, never login tokens.');}
function importDialog(){let parsed=null;modal('Bring your people with you.',`<p>Choose a V2 JSON export or V3 backup. Existing IDs are skipped, never overwritten. Keep the original file, which retains any pending conflict versions.</p><label>Backup JSON<input id="import-file" type="file" accept="application/json,.json" required></label><div id="import-summary" class="notice">Choose a file to preview.</div>${key!=='local'?'<p class="notice warn">Imported contacts and history will be uploaded to your connected Supabase account when sync runs.</p>':''}`,async()=>{if(!parsed)throw Error('Select a valid export first.');let added=0;await mutate(key,s=>{for(const [id,r] of Object.entries(parsed.contacts)){if(!s.contacts[id]){s.contacts[id]=r;added++;}}for(const [id,n] of Object.entries(parsed.notes))if(!s.notes[id])s.notes[id]=n;s.audit.push(...parsed.legacyAudit);s.imports.push({at:new Date().toISOString(),source:parsed.source,added});});toast(`Imported ${added} new contacts. Existing records were preserved.`);kick();},'Import these records');$('#import-file').onchange=async e=>{parsed=null;try{const file=e.target.files[0];if(!file||file.size>20000000)throw Error('Choose a JSON file under 20 MB.');parsed=await prepareImport(JSON.parse(await file.text()));$('#import-summary').textContent=`${Object.keys(parsed.contacts).length} contacts and ${Object.keys(parsed.notes).length} history entries. ${parsed.source}.`;}catch(e){$('#import-summary').textContent=e.message;}};}
async function runSync(){if(busy||key==='local'||!cloud?.session)return;busy=true;syncError='';render();try{await synchronize(key,cloud);auto=true;toast('Sync complete.');}catch(e){syncError=e.message;auto=false;}finally{busy=false;await refresh();}}
function kick(){if(auto&&navigator.onLine&&key!=='local')setTimeout(runSync,100);}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;try{
 if(a==='close')return $('#dialog').close();
 if(a==='contacts'||a==='back'){view='contacts';selected=null;await refresh();}
 else if(a==='settings'){view='settings';selected=null;await refresh();}
 else if(a==='open'){selected=id;view='contacts';await refresh();}
 else if(a==='add')edit();else if(a==='edit')edit(id);else if(a==='note')note(id);else if(a==='resolve')conflict(id);else if(a==='outreach')outreach(id);
 else if(a==='save-event'){const event=$('#event').value;await mutate(key,s=>s.event=event);toast('Event remembered on this device.');await refresh();}
 else if(a==='trash'){trash=!trash;render();}
 else if(a==='sync')await runSync();else if(a==='configure')configure();else if(a==='export')download();else if(a==='import')importDialog();
 else if(a==='archive'){const r=state.contacts[id];if(r.conflict)throw Error('Review this contact’s conflict first.');modal(r.draft.deleted?'Restore contact?':'Archive contact?',`<p>${esc(r.draft.name)} and their history remain recoverable. Changes on another device may require conflict review.</p>`,async()=>{await mutate(key,s=>{if(!equal(s.contacts[id].draft,r.draft)||s.contacts[id].conflict)throw Error('Contact changed; reopen this action.');s.contacts[id].draft.deleted=!r.draft.deleted;});kick();},r.draft.deleted?'Restore':'Archive');}
 else if(a==='signout'){if(busy)throw Error('Wait for sync to finish.');cloud.signout();key='local';syncError='';selected=null;toast('Signed out locally. Account cache is retained for your next sign-in on this trusted device.');await refresh();}
 else if(a==='forget'){modal('Remove this device’s copy?',`<p>This clears this workspace’s local contacts, notes, and pending edits from this browser. Cloud records stay unchanged. Export a backup first; unsynced edits cannot be retrieved from the cloud.</p><label class="check"><input type="checkbox" required>I have saved a backup and want to remove this cached workspace.</label>`,async()=>{if(busy)throw Error('Wait for sync to finish.');await forget(key);if(key!=='local')cloud.signout();key='local';selected=null;toast('Local cache removed.');},'Remove local copy');}
 }catch(e){err(e);}});
window.addEventListener('online',()=>{toast('Back online.');kick();});window.addEventListener('offline',()=>{toast('Offline. Edits stay on this device.');render();});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){refresh().then(kick).catch(err);}});
setInterval(()=>{if(!document.hidden&&!$('#dialog').open&&!document.activeElement?.matches('input,textarea,select'))kick();},30000);
try{sessionConfig();await refresh();if('serviceWorker'in navigator){await navigator.serviceWorker.register('./sw.js');}kick();}catch(e){err(e);$('#main').innerHTML='<div class="notice error">Could not open local storage. Enable browser storage and use a supported browser. No edits have been saved.</div>';}

window.addEventListener('storage',e=>{
 if(cloud&&e.key===cloud.key){
  try{const next=JSON.parse(e.newValue||'null');if(next?.user?.id!==cloud.userId){cloud.session=null;key='local';selected=null;syncError='';auto=false;toast('Account changed in another tab. Returned to local workspace.');refresh().catch(err);}}catch(error){err(error);}
 }
});
